import classNames from "classnames";
import { createElement } from "react";

export default function Container({
    children,
    height = false,
    flex = false,
    flexRow = false,
    flexRowReverse = false,
    flexCol = false,
    flexColReverse = false,
    justifyNormal = false,
    justifyStart = false,
    justifyEnd = false,
    justifyCenter = false,
    justifyBetween = false,
    justifyAround = false,
    justifyEvenly = false,
    justifyStretch = false,
    itemsStart = false,
    itemsEnd = false,
    itemsCenter = false,
    itemsBaseline = false,
    itemsStretch = false,
    placeContentCenter = false,
    placeContentStart = false,
    placeContentEnd = false,
    placeContentBetween = false,
    placeContentAround = false,
    placeContentEvenly = false,
    placeContentBaseline = false,
    placeContentStretch = false,
}) {
    return createElement('section', {
        className: classNames("max-w-screen-2xl mx-auto p-6 gap-4 py-12", {
            [`h-[${height}]`]: (typeof height === 'string'),
            ['flex']: flex,
            ['flex-row']: (flexRow),
            ['flex-row-reverse']: (flexRowReverse),
            ['flex-col']: (flexCol),
            ['flex-col-reverse']: (flexColReverse),
            ['justify-normal']: (flex && justifyNormal),
            ['justify-start']: (flex && justifyStart),
            ['justify-end']: (flex && justifyEnd),
            ['justify-center']: (flex && justifyCenter),
            ['justify-between']: (flex && justifyBetween),
            ['justify-around']: (flex && justifyAround),
            ['justify-evenly']: (flex && justifyEvenly),
            ['justify-stretch']: (flex && justifyStretch),
            ['items-start']: (flex && itemsStart),
            ['items-end']: (flex && itemsEnd),
            ['items-center']: (flex && itemsCenter),
            ['items-baseline']: (flex && itemsBaseline),
            ['items-stretch']: (flex && itemsStretch),
            ['place-content-center']: (flex && placeContentCenter),
            ['place-content-start']: (flex && placeContentStart),
            ['place-content-end']: (flex && placeContentEnd),
            ['place-content-between']: (flex && placeContentBetween),
            ['place-content-around']: (flex && placeContentAround),
            ['place-content-evenly']: (flex && placeContentEvenly),
            ['place-content-baseline']: (flex && placeContentBaseline),
            ['place-content-stretch']: (flex && placeContentStretch),
        })
    }, children)
}